chore|build and create github release

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -4,13 +4,13 @@
 HOOK_DIR="$(cd "$(dirname "$0")" && pwd)"
 . "$HOOK_DIR/lib.sh"
 
-echo "Running Ruff ..."
-enqueue_sound  "$RUFF_SOUND"
+
 
 cd "$REPO_ROOT"
 
 # Type
 
+echo "Running Type Check ..."
 mypy . 
 
 mypy_status=$?
@@ -22,7 +22,8 @@ if [ $mypy_status -ne 0 ]; then
 fi
 
 # Linter
-
+echo "Running Ruff ..."
+enqueue_sound  "$RUFF_SOUND"
 ruff check .
 
 ruff_status=$?
@@ -34,6 +35,8 @@ if [ $ruff_status -ne 0 ]; then
 fi
 
 # Format
+
+echo "Running Formatter (black)..."
 black --check .
 
 black_status=$?
@@ -54,11 +57,33 @@ fi
 
 # Tests
 
+echo "Running Tests..."
 pytest .
+
 
 pytest_status=$?
 
 if [ $pytest_status -ne 0 ]; then
+    echo "Tests failed"
+    enqueue_sound  "$(pick_random_failure_sound)"
+    exit 1
+fi
+
+
+# Build
+
+echo "Building..."
+enqueue_sound  "$BUILD_SOUND"
+
+pyinstaller main.py \
+  --name MessedUpFarm \
+  --onefile \
+  --add-data "client/src/assets;client/src/assets" \
+  --windowed
+
+build_status=$?
+
+if [ build_status -ne 0 ]; then
     echo "Tests failed"
     enqueue_sound  "$(pick_random_failure_sound)"
     exit 1
