chore|added code coverage

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -55,14 +55,11 @@ fi
 # Tests
 TEST_COVERAGE=1
 
-pytest --cov=. --cov-fail-under=$TEST_COVERAGE
 
-pytest_status=$?
-
-if [ $pytest_status -ne 0 ]; then
-    echo "Tests failed or Test Coverage is below $TEST_COVERAGE"
-    enqueue_sound  "$(pick_random_failure_sound)"
+pytest --cov=. --cov-fail-under=$TEST_COVERAGE || {
+    echo "Tests failed or coverage too low"
+    enqueue_sound "$(pick_random_failure_sound)"
     exit 1
-fi
+}
 
 enqueue_sound  "$(pick_random_success_sound)"
