added mypy and clean code .sh

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -9,18 +9,46 @@ enqueue_sound  "$RUFF_SOUND"
 
 BEFORE=$(git diff --name-only)
 
-# Linter and Format
 cd "$REPO_ROOT"
+
+# Type
+
+mypy .
+
+mypy_status=$?
+
+if [ $mypy_status -ne 0 ]; then
+    echo "Commit blocked: Type Errors to fix"
+    enqueue_sound  "$(pick_random_no_sound)"
+    exit 1
+fi
+
+# Linter
 
 ruff check . --fix
 
+if [ $ruff_status -ne 0 ]; then
+    echo "Committ blocked: Ruff linted ... Please re-stage changes and commit again"
+    enqueue_sound  "$(pick_random_failure_sound)"
+    exit 1
+fi
+
+# Format
+
 black .
+
+if [ $black_status -ne 0 ]; then
+    echo "Commit blocked: Black formatted to format the code"
+    enqueue_sound  "$(pick_random_failure_sound)"
+    exit 1
+fi
+
+# Double Check
 
 AFTER=$(git diff --name-only)
 
 if [ "$BEFORE" != "$AFTER" ]; then
-    echo "⚠️ Ruff modified files"
-    echo "Please re-stage changes and commit again"
+    echo "Commit blocked: Please fix any errors, re-stage changes and commit again"
     enqueue_sound  "$(pick_random_no_sound)"
     exit 1
 fi
diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -9,6 +9,18 @@ enqueue_sound  "$RUFF_SOUND"
 
 cd "$REPO_ROOT"
 
+# Type
+
+mypy . 
+
+mypy_status=$?
+
+if [ $mypy_status -ne 0 ]; then
+    echo "Push blocked: Type Errors to fix"
+    enqueue_sound  "$(pick_random_failure_sound)"
+    exit 1
+fi
+
 # Linter
 
 ruff check .
@@ -31,6 +43,8 @@ if [ $black_status -ne 0 ]; then
     enqueue_sound  "$(pick_random_failure_sound)"
     exit 1
 fi
+
+# Double Check
 
 if ! git diff --quiet; then
     echo "Push blocked: formatting issues detected"
