21 chore implement mypy for static type checking (#26)
* fix|playing sound to play using full address

* fix|playing sound to play using full address

* chore|deduplicate code, convert pre-push to sh, and added ruff to pre-push

* fix| 2 linter errors

* pre-commit handles BEFORE|AFTER for git -diff

* chore/audio runs without dealying git action

* fix| indendation in lint.yml

* fix| lint.yml location

* chore|add black to format

* chore|start sound worker sooner

* fix|mypy errors

* fix|ruff errors

* chore|rename .yml file

* merged

* merged

* added mypy and clean code .sh

* fix pre-commit

* Automatically added GitHub issue links to TODOs

* fixed workflow

* added mypy

* Update .githooks/pre-commit

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Add shebang to clean_code.sh

* Update .githooks/pre-commit

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Update scripts/clean_code.sh

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* fixed work flow?

* fixed work flow?

---------

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -9,17 +9,33 @@ enqueue_sound  "$RUFF_SOUND"
 
 cd "$REPO_ROOT"
 
+# Type
+
+mypy . 
+
+mypy_status=$?
+
+if [ $mypy_status -ne 0 ]; then
+    echo "Push blocked: Type Errors to fix"
+    enqueue_sound  "$(pick_random_failure_sound)"
+    exit 1
+fi
+
 # Linter
+
 ruff check .
 
-if [ $? -ne 0 ]; then
+ruff_status=$?
+
+if [ $ruff_status -ne 0 ]; then
     echo "Push blocked: Ruff lint errors detected"
     enqueue_sound  "$(pick_random_failure_sound)"
     exit 1
 fi
 
 # Format
-black .
+black --check .
+
 black_status=$?
 
 if [ $black_status -ne 0 ]; then
@@ -27,6 +43,9 @@ if [ $black_status -ne 0 ]; then
     enqueue_sound  "$(pick_random_failure_sound)"
     exit 1
 fi
+
+# Double Check
+
 if ! git diff --quiet; then
     echo "Push blocked: formatting issues detected"
     enqueue_sound  "$(pick_random_failure_sound)"
